fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "mysql":
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
      ref:  'origin/0.x'
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "rabbitmq":
      repo: "git://github.com/puppetlabs/puppetlabs-rabbitmq"
      ref: 'origin/2.x'
    'inifile':  'git://github.com/cprice-puppet/puppetlabs-inifile'
    "postgresql": "git://github.com/puppetlabs/puppet-postgresql.git"
  symlinks:
    "glance": "#{source_dir}"
