name         'puppetlabs-glance'
version      '4.0.0'
author       'Puppet Labs and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Glance'
description  'Installs and configures OpenStack Glance (Image Service).'
project_page 'https://launchpad.net/puppet-glance'
source       'https://github.com/stackforge/puppet-glance'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/stdlib', '>=4.0.0 <5.0.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
